import Navbar from './js/interface/Nav'
import Contact from './js/interface/Contact'
import Home from './js/pages/Home'    
import Portafolio from './js/pages/Portafolio'
import Not4u from './js/pages/Not4u'